name: Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: microservices/echo
          tags: andoshin11/echo-service:${{ github.sha }}
